keys:
  - &c4patino_arisu age1redpndk4tj0jy6d8cl98rkt5euxzpfzc8dvlhfan5a349tl7tg5s5j6zav
  - &c4patino_arisu_windows age1sq60xvdnp2r7m0n3a72pgqee26uqe5k5azqjms0vjpcjggpmgqlqvql9e0
  - &c4patino_kokoro age1u0jz3r6tz3a7rz64j02xpwuykslq9zruxasutvmum07ya7k3xduseme93n 
  - &c4patino_kokoro_windows age1qq0x7cpk5yg70htdm4dywc4glyx22c4uu78d50t8lax69f7kpp7skspslr
  - &c4patino_chibi age1r9285z8xmtj7g6alau7xp946p4fguvtd62dz05nvfgxyujhmfs7svp0uyw
  - &c4patino_shiori age185cchggrqp8v9wryj7npdvv3h2z735zamtqgchu5tltmjmpsaehsteyrpk

creation_rules:
  - path_regex: secrets/sops/secrets.yaml
    key_groups:
      - age:
        - *c4patino_arisu
        - *c4patino_arisu_windows
        - *c4patino_kokoro
        - *c4patino_kokoro_windows
        - *c4patino_chibi
        - *c4patino_shiori
  - path_regex: secrets/sops/arisu.yaml
    key_groups:
      - age:
        - *c4patino_arisu
  - path_regex: secrets/sops/arisu-windows.yaml
    key_groups:
      - age:
        - *c4patino_kokoro
        - *c4patino_arisu_windows
  - path_regex: secrets/sops/kokoro.yaml
    key_groups:
      - age:
        - *c4patino_kokoro
  - path_regex: secrets/sops/kokoro-windows.yaml
    key_groups:
      - age:
        - *c4patino_kokoro
        - *c4patino_kokoro_windows
  - path_regex: secrets/sops/chibi.yaml
    key_groups:
      - age:
        - *c4patino_chibi
  - path_regex: secrets/sops/shiori.yaml
    key_groups:
      - age:
        - *c4patino_shiori
